config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'singup', to: 'users#new', as: 'singup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#edit', as: 'profile'
  get 'users', to: 'users#index', as: 'users'
  get 'home', to: 'posts#index', as: 'home'
  get 'tags/:tag', to: 'posts#index', as: "tag"

  resources :users do
    resources :posts
  end
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
    resources :comments
  end

  get 'home/index'
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  validates :name,  :presence => true
  validates :title, :presence => true

  acts_as_votable

  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :taggings
  has_many :tags, through: :taggings

  accepts_nested_attributes_for :tags, :allow_destroy => :true,
                                :reject_if => proc { |attrs| attrs.all? { |k, v| v.blank? } }
  def self.tagged_with(name)
    Tag.find_by_name!(name).posts
  end
  def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end

  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  #before_action :current_user, :except => [:index, :show]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.all
    end
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end
  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.liked_by current_user
    redirect_to @post
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_from current_user
    redirect_to @post
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:name, :title, :content, :cshow, :user_id, :all_tags)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ")
  end
end

app/views/posts/_form.html.erb
<% @post.tags.build %>
    <%= form_for(@post) do |post_form| %>
        <% if @post.errors.any? %>
            <div id="errorExplanation">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
              <ul>
                <% @post.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>
        <%= post_form.hidden_field :user_id, :value => current_user.id%>
        <div class="field">
          <%= post_form.label :name %><br />
          <%= post_form.text_field :name %>
        </div>
        <div class="field">
          <%= post_form.label :title %><br />
          <%= post_form.text_field :title %>
        </div>
        <div class="field">
          <%= post_form.label :content %><br />
          <%= post_form.text_area :content %>
        </div>
        <div>
          <td><%= post_form.label 'Comments approved', 'Comments approved' %></td>
          <td><%= post_form.radio_button :cshow, 1 %></td>
        </div>

        <div>
          <td><%= post_form.label 'Comments not approved', 'Comments not approved' %></td>
          <td><%= post_form.radio_button :cshow, 2 %></td>
        </div>

        <h2>Tags</h2>
        <div class="field">
          <%= post_form.label :all_tags, "Tags (separated by commas)" %><br />
          <%= post_form.text_field :all_tags %>
        </div>
        <div class="actions">
          <%= post_form.submit %>
        </div>
<% end %>

app/views/posts/edit.html.erb
<% if current_user %>
<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>
<%end%>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-default' %>
<% end %>

<table id="posts_table" class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content[0..511] %></td>
        <td><%= link_to 'Show', post, class: 'btn btn-default' %></td>
        <% if owned post%>
          <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default' %></td>
          <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
        <% end %>
        <%if current_user%>
        <% if admin %>
            <td><%= link_to 'Edit', edit_post_path(post), class: 'btn btn-default' %></td>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default' %></td>
        <% end %>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<% @tags.all.each do |tag| %>
    <%= link_to tag.name, tag_path(tag.name) %>
<% end %>

app/views/posts/new.html.erb
<% if current_user %>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>
<%end%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="jumbotron">
    <h1>
      <%= @post.title%>
    </h1>


    <p>
      <%= @post.content %>
    </p>
    </div>

<p><%= link_to image_tag("like.png", border: 0), like_post_path(@post), method: :put %> <%= @post.get_likes.size %> &nbsp;&nbsp;&nbsp;&nbsp;
<%= link_to image_tag("dislike.png", border: 0), dislike_post_path(@post), method: :put %> <%= @post.get_dislikes.size %></p>

<p>
  <strong>Tags:</strong>
  <%=raw tag_links(@post.all_tags)%>
</p>
<% if @post.cshow==1 %>
    <h3>Comments</h3>
    <% if current_user %>
      <%= form_for [@post, Comment.new] do |f| %>
          <%= f.hidden_field :commenter, :value => current_user.email%>
          <%= f.text_area :body, placeholder: "Add a comment" %><br/>
          <%= f.submit "Add Comment" %>
      <% end %>
    <% end %>
      <ul>
        <%= render(partial: 'comments/comment', collection: @post.comments) %>
      </ul>
<% end %>
    <% if owned @post%>
<%= link_to 'Edit', edit_post_path(@post) %> |
    <%end%>
<%= link_to 'Back', posts_path %>
</div>