config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :sessions, only: [:new, :create, :destroy]
  
  get 'singup', to: 'users#new', as: 'singup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'profile', to: 'users#edit', as: 'profile'
  get 'users', to: 'users#index', as: 'users'
  get 'home', to: 'posts#index', as: 'home'
  get 'tags/:tag', to: 'posts#index', as: "tag"

  resources :users do
    resources :posts
  end
  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments
  end
  resources :comments do
    member do
      put "like", to: "comments#upvote"
      put "dislike", to: "comments#downvote"
    end
    resources :comments
  end

  get 'home/index'
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style=>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-header">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div i="user_header">
      <% if current_user %>
          <font color="white">Looged in as <%= current_user.email %></font>.
          <a class="navbar-brand" href="#"><%= link_to "Log Out", logout_path %></a><br>
          <h5>
            <%= link_to "Home", home_path %>
            <%= link_to "Profile", profile_path %>
            <% if admin %>
            <%= link_to "Users", users_path %>
            <%end%>
          </h5>
      <%else%>
          <a class="navbar-brand" href="#"><%= link_to "Sing Up", singup_path %> </a>|
          <a class="navbar-brand" href="#"><%= link_to "Log In", login_path %> </a>
      <% end %>
    </div>
  </div>
  <!-- /.container -->
</nav>
<br>



<% flash.each do |key, value| %>
    <% content_tag(:div, class: "alert alert-#{key}") do%>
        <p><%= value%></p>
    <% end %>
<% end %>

<%= yield %>
</body>
</html>